# Generated by Django 6.0.1 on 2026-01-27 11:24

import loan.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='maximo_retorno',
            field=models.DateTimeField(default=loan.models.get_maximo_retorno, verbose_name='Fecha límite'),
        ),
    ]
