# Generated by Django 6.0.1 on 2026-01-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='authors/', verbose_name='Imagen'),
        ),
    ]
