# Generated by Django 6.0.1 on 2026-01-27 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('summary', models.TextField(help_text='De qué trata el libro', verbose_name='Resumen')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('stock', models.PositiveIntegerField(default=1, verbose_name='Ejemplares disponibles')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Portada')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='author.author')),
            ],
        ),
    ]
